#!/usr/bin/env bash

set -eE

_header() {
  echo -e "\e[1;32m\n## $*\e[0m"
}

_help() {

cat <<EOF

 Usage: 

 ./test-cryosparc.sh <email> <project_dir> <cluster>

EOF

exit -1

}

get_project_id() {
 cryosparcm cli "list_projects()" |\
 python3 -c "import sys, ast; [print(p['uid']) for p in ast.literal_eval(sys.stdin.read()) if 'OSC test workers' in p.get('title', '')]" |\
 head -n 1
}

EMAIL=$1
PROJECT_DIR=$2
CLUSTER=$3

if [[ -z "$EMAIL" ]] || [[ -z "$PROJECT_DIR" ]] || [[ -z "$CLUSTER" ]] ; then
  _help
fi

export TERM=linux
cd /opt/cryosparc_master/run/

_header "Test checklist"
cryosparcm test install

email_address=$1
user_id=$(cryosparcm cli "get_id_by_email('$email_address')")
echo "User ID is: $user_id"

_header "Create a project"
project_uid=$(get_project_id)
if [[ "$project_uid" == "P"* ]]; then
  echo "Found the project with UID: $project_uid"
else
  project_container_dir=$2
  mkdir -p ${project_container_dir}
  project_title="OSC test workers"
  project_uid=$(cryosparcm cli "create_empty_project(owner_user_id='$user_id', project_container_dir='$project_container_dir', title='$project_title')")
  echo "Created project with UID: $project_uid"
fi

_header "Test workers on $CLUSTER"
current_values=$(cryosparcm cli "get_cluster_configuration_custom_vars()" | tr -d '{}')
cryosparcm cli "set_cluster_configuration_custom_vars({$current_values, 'time': 60})"
cryosparcm test workers $project_uid --target $CLUSTER
